name: multimodalgenai
channels:
  - conda-forge
dependencies:
  - python=3.8
  # PYTHON AND JUPYTER BASICS
  - pip
  - ipython
  - tqdm
  - joblib
  - jupyterlab
  # DATA SCIENCE BASICS
  - pandas
  - numpy
  - matplotlib
  - seaborn
  # NLP
  - spacy=3.4.1
  - wordcloud=1.8.2.2
  - stringcase=1.2.0
  - pip:
      - -e .  # install sapsam project in editable mode
      - spacy_langdetect  # not available in conda-forge
      - language_data
      - scikit-learn
      - sentence-transformers
      - networkx[default]
      - pm4py
      - openai
      - pypdfium2
      - langchain
      - typing-inspect==0.8.0 # fixing langchain dependency error https://stackoverflow.com/questions/76313592/import-langchain-error-typeerror-issubclass-arg-1-must-be-a-class
      - typing_extensions==4.5.0 # same as above
      - pydantic==1.10.11 # same as above
      - selenium
      - Flask
