### Tasks
### Diefferent task elements: Task, CollapsedSubprocess, Subprocess, CollapsedEventSubprocess, EventSubprocess
### Different task types:


### Events: StartNoneEvent, StartMessageEvent, StartTimerEvent, StartEscalationEvent, StartConditionalEvent, StartErrorEvent, StartCompensationEvent, StartSignalEvent, StartMultipleEvent, StartParallelMultipleEvent
### Different event types:

sapsam_mapping = {
    "BPMNDiagram": "Diagram",
    "Task": "Activities",
    "CollapsedSubprocess": "Activities",
    "Subprocess": "Activities",
    "CollapsedEventSubprocess": "Activities",
    "EventSubprocess": "Activities",
    "Exclusive_Databased_Gateway": "Gateways",
    "EventbasedGateway": "Gateways",
    "ParallelGateway": "Gateways",
    "InclusiveGateway": "Gateways",
    "ComplexGateway": "Gateways",
    "Pool": "Pools",
    "CollapsedPool": "Pools",
    "Lane": "Lanes",
    "VerticalPool": "Pools",
    "CollapsedVerticalPool": "Pools",
    "VerticalLane": "Lanes",
    "processparticipant": "Artifacts",
    "Group": "Artifacts",
    "TextAnnotation": "Artifacts",
    "DataObject": "Data Elements",
    "ITSystem": "Artifacts",
    "DataStore": "Data Elements",
    "Message": "Data Elements",
    "StartNoneEvent": "Events",
    "StartMessageEvent": "Events",
    "StartTimerEvent": "Events",
    "StartEscalationEvent": "Events",
    "StartConditionalEvent": "Events",
    "StartErrorEvent": "Events",
    "StartCompensationEvent": "Events",
    "StartSignalEvent": "Events",
    "StartMultipleEvent": "Events",
    "StartParallelMultipleEvent": "Events",
    "IntermediateMessageEventCatching": "Events",
    "IntermediateTimerEvent": "Events",
    "IntermediateEscalationEvent": "Events",
    "IntermediateConditionalEvent": "Events",
    "IntermediateLinkEventCatching": "Events",
    "IntermediateErrorEvent": "Events",
    "IntermediateCancelEvent": "Events",
    "IntermediateCompensationEventCatching": "Events",
    "IntermediateSignalEventCatching": "Events",
    "IntermediateMultipleEventCatching": "Events",
    "IntermediateParallelMultipleEventCatching": "Events",
    "IntermediateEvent": "Events",
    "IntermediateMessageEventThrowing": "Events",
    "IntermediateEscalationEventThrowing": "Events",
    "IntermediateLinkEventThrowing": "Events",
    "IntermediateCompensationEventThrowing": "Events",
    "IntermediateSignalEventThrowing": "Events",
    "IntermediateMultipleEventThrowing": "Events",
    "EndNoneEvent": "Events",
    "EndMessageEvent": "Events",
    "EndEscalationEvent": "Events",
    "EndErrorEvent": "Events",
    "EndCancelEvent": "Events",
    "EndCompensationEvent": "Events",
    "EndSignalEvent": "Events",
    "EndMultipleEvent": "Events",
    "EndTerminateEvent": "Events",
    "SequenceFlow": "Sequence Flows",
    "Association_Undirected": "Associations",
    "Association_Unidirectional": "Associations",
    "Association_Bidirectional": "Associations",
    "MessageFlow": "Message Flows"
}


